spring.application.name=BillingSystem
# MySQL DB connection
spring.datasource.url=jdbc:mysql://localhost:3307/pahana-edu-billing-system
spring.datasource.username=root
spring.datasource.password=root

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server
server.port=8000